### ISSUE TITLE
exe build failure per -Werror

### ISSUE THREAD

**Issue by DanBurton** [LeventErkok/crackNum#7]
On the stackage build server there was a build failure on the `crackNum` executable (due to specifying `-Werror` in `Main.hs`):

```
Building executable 'crackNum' for crackNum-3.4..
[1 of 3] Compiling CrackNum.TestSuite
[2 of 3] Compiling Paths_crackNum
[3 of 3] Compiling Main

/Users/dan/scratch/crackNum-3.4/src/CrackNum/Main.hs:340:78: error: [GHC-63394] [-Wx-partial, -Werror=x-partial]
    In the use of ‘tail’
    (imported from Prelude, but defined in GHC.List):
    "This is a partial function, it throws an error on empty lists. Replace it with drop 1, or use pattern matching or Data.List.uncons instead. Consider refactoring to use Data.List.NonEmpty."
    |
340 |                 trim xs | "[" `isPrefixOf` xs && "]" `isSuffixOf` xs = init (tail xs)
    |                                                                              ^^^^
```

I was able to reproduce this locally like so:

```bash
stack unpack crackNum-3.4 && cd crackNum-3.4
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: nightly-2024-01-11
extra-deps:
- sbv-10.3@sha256:d869a49fd8e6303a81f7f704bb8669deff20d000e4644f93ddc64749d4bc0f9a,23712

```
